@startuml login
autonumber

title Snapay Login Cusomer and Merchant

header
    User Action: Initiating a POST request to the '/process-order' endpoint
endheader

caption Login Workflow


skinparam NoteBackgroundColor #LightGrey
skinparam TitleBackgroundColor #Pink
skinparam ParticipantBackgroundColor #Orange
skinparam ActorBackgroundColor #Orange
skinparam DatabaseBackgroundColor #Purple
skinparam BoundaryBackgroundColor #LightGreen
skinparam ControlBackgroundColor #Yellow

actor User <<(U, LightGreen)>>
boundary "Snapay Mobile App" as UI
participant "Snapay API" as API <<(A, LightBlue)>>
control "Redis Service" as redis <<(R, Red)>>
participant " Bank API" as BankAPI <<(B, LightBlue)>>
database "Snapay Database" as Database <<(D, SkyBlue)>>

User -> UI : Clicks on add new wallet
note left : The user is on wallet screen
UI -> UI : Display wallet creation form
User -> UI : Enters wallet name adds bank information
UI -> API : POST /wallets/create
API -> redis : Storre Wallet details
note left : store the information for easy access
redis -> API : Succesful
API -> BankAPI : Verify bank details
alt#yellow  #LightSalmon verification failed
    BankAPI -> API : 400 Bad reuquest
    note left : Api may return specific error message
    API -> UI : Error Message 
    UI-> UI : Display error message
    User -> UI : Resolve error message
else #LightGreen
    BankAPI ->  API : 200 Success
    API ->  redis : retrieve wallet details
    API -> API : Genereate unique wallet id
    API -> Database : store wallet in database
    Database ->  API :Success 
    API -> UI : SUccess Message - Walet Created
    UI -> UI : Display success message
end


@enduml